title: KnowOcean
description: >- # this means to ignore newlines until "endquote"
  A simple Jekyll site using a remote theme.
url: "https://know-ocean.github.io" # your website URL, change as needed

remote_theme: daviddarnes/alembic@main

# Optional settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-remote-theme
