title: "KnowOcean"
description: "Resources for the aspiring marine biologist"
url: "https://know-ocean.github.io"
baseurl: ""

remote_theme: daviddarnes/alembic@main

markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-remote-theme

sass:
  style: compressed

permalink: pretty
timezone: US/Pacific
lang: en-US

css_inline: false

navigation_header:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Blog
    url: /blog/
  - title: Search
    url: /search/
